---
- name: Базовая настройка CentOS 9
  hosts: all
  become: true
  tasks:
    - name: Обновление всех пакетов с использованием yum
      yum:
        name: "*"
        state: latest

    - name: Установка epel-release
      yum:
        name: epel-release
        state: present

    - name: Установка vim
      yum:
        name: vim
        state: present

    - name: Установка htop
      yum:
        name: htop
        state: present
